server:
  port: 8080

spring:
  application:
    name: client-api
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

# Custom Multi-Tenant Configuration
# We will load these properties into a custom configuration class
tenants:
  datasources:
    - tenantId: tenant1
      url: jdbc:sqlserver://localhost:1433;databaseName=db_tenant1;encrypt=false;trustServerCertificate=true
      username: sa
      password: password
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    - tenantId: tenant2
      url: jdbc:sqlserver://192.168.1.100:1433;databaseName=db_tenant2;encrypt=false;trustServerCertificate=true
      username: sa
      password: password
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    - tenantId: default
      url: jdbc:sqlserver://192.168.110.193:1433;databaseName=FY_SALDB;encrypt=false;trustServerCertificate=true
      username: fongyisa
      password: F0ngY!$@
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    # Add more tenants here...

line:
  bot:
    channel-token: 'YOUR_CHANNEL_TOKEN'
    channel-secret: 'YOUR_CHANNEL_SECRET'
    handler:
      path: /callback
