server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: client-api
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

# Custom Multi-Tenant Configuration
# We will load these properties into a custom configuration class
tenants:
  datasources:
    - tenantId: tenant1
      url: jdbc:mysql://localhost:3306/db_tenant1
      username: root
      password: password
      driverClassName: com.mysql.cj.jdbc.Driver
    - tenantId: tenant2
      url: jdbc:mysql://192.168.1.100:3306/db_tenant2
      username: root
      password: password
      driverClassName: com.mysql.cj.jdbc.Driver
    # Add more tenants here...

line:
  bot:
    channel-token: 'YOUR_CHANNEL_TOKEN'
    channel-secret: 'YOUR_CHANNEL_SECRET'
    handler:
      path: /callback
